---
title: "Factors"
author: "Ashlee"
date: "4/25/2022"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.path = '../Output/')
```

Today we will be working with factors. 
A factor is a specialized version of a character. 

# Libraries 
```{r, warning=FALSE, message=FALSE}
library(tidyverse)
library(here)
```
# Data 
```{r, warning=FALSE, message=FALSE}
income_mean <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-09/income_mean.csv')
```
To make something a factor you must use the factor function. 
```{r, warning=FALSE, message=FALSE}
fruits<-factor(c("Apple", "Grape", "Banana"))
fruits
```
Working with starwars package 
```{r, warning=FALSE, message=FALSE}
glimpse(starwars) 

star_counts <- starwars %>% 
  filter(!is.na(species)) %>% # remove nas 
  mutate(species = fct_lump(species, n= 3)) %>% # lump species into three different categories where top three stay same and everything else turns into other 
  count(species, sort = TRUE)

star_counts

```
# Creating plot 
```{r starcounts, warning=FALSE, message=FALSE}
star_counts %>% 
  ggplot(aes(x = fct_reorder(species, n), y = n))+ # reorder the factor of species by n
  geom_col() +
  labs(x = "Species")
```
Rendering Line Plots 
```{r line graph, message=FALSE, warning=FALSE}
glimpse(income_mean)

total_income<-income_mean %>%
  group_by(year, income_quintile)%>%
  summarise(income_dollars_sum = sum(income_dollars))%>%
  mutate(income_quintile = factor(income_quintile)) # make it a factor

total_income%>%
ggplot(aes(x = year, y = income_dollars_sum, 
           color = fct_reorder2(income_quintile, year, income_dollars_sum)))+ # reorder income quintile by year then by dollar sum 
  geom_line()+
  labs(color = "income quantile")
```

```{r, warning=FALSE, message=FALSE}
x1 <- factor(c("Jan", "Mar", "Apr", "Dec"), levels = c("Jan", "Mar", "Apr", "Dec")) # levels are the order you want it to be 
x1

```
Subsetting data with factors
```{r, warning=FALSE, message=FALSE}
starwars_clean<-starwars %>% 
  filter(!is.na(species)) %>% # remove the NAs
  count(species, sort = TRUE) %>%
  mutate(species = factor(species)) %>% # make species a factor
  filter(n>3) %>%  # only keep species that have more than 3
  droplevels() %>% #drop extra levels
  mutate(species = fct_recode(species, "Humanoid" = "Human")) # recode or rename level. give name of column, what you want the new name to be and what the old name was 
starwars_clean

levels(starwars_clean$species)
```

